### ISSUE TITLE
support Gnome 3.8

### ISSUE THREAD

**Issue by killarny** [killarny/gedit-python-outline#3]
Gnome 3.8 requires Python 3, and the python3-logilab-astng module has some api differences that make existing code for gedit-python-outline not function.

There is some initial work on this in [feature/gnome3.8-support](https://github.com/killarny/gedit-python-outline/commits/feature/gnome3.8-support)

**Comment by stuaxo** [comment]
Cool ..    I hacked a bit on the gnome-3.8-support branch   https://github.com/killarny/gedit-python-outline/pull/5

At least it loads up and shows the error in the outline bar - when loading itself the line number seems right, the error message looks like it's in logilab .. and I only heard of that yesterday :)

Pretty much just bashed it till it worked some more, so no idea if the changes are right..

**Comment by stuaxo** [comment]
OK, turns out logilab is now called 'astroid', updated my commit and the sidebar seems to actually work :)

New pull request..
https://github.com/killarny/gedit-python-outline/pull/6

Main thing I'm not sure about if the is the docstring thingy.
